# Generated by Django 3.2.19 on 2023-06-19 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('private_info', '0002_contact_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='time',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='time',
        ),
        migrations.AddField(
            model_name='diary',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='diary',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='memo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
