# Generated by Django 3.2.19 on 2023-06-19 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private_info', '0003_auto_20230620_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater_memo', to=settings.AUTH_USER_MODEL),
        ),
    ]
