# Generated by Django 3.2.19 on 2023-06-19 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private_info', '0004_memo_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater_diary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater_financial', to=settings.AUTH_USER_MODEL),
        ),
    ]
