# Generated by Django 3.2.19 on 2023-06-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_info', '0005_auto_20230620_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
