# Generated by Django 3.2.19 on 2023-06-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_info', '0007_alter_financialrecord_expense_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='remaining_funds',
        ),
    ]
